name: Deploy AWS

on:
  push:
    branches:
      - main

jobs:
  AWS_DEPLOY:
    runs-on: self-hosted
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Create front-end .env
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_REACT_APP_API_BASE_URL: ${{secrets.REACT_APP_API_BASE_URL}}
          directory: .
          file_name: .env.production
          fail_on_empty: true
      
      - name: Build
        run: docker-compose down && docker-compose build
      
      - name: Run
        run: docker-compose down -v && docker-compose up -d